### ISSUE TITLE
测试过带密码的情况吗？带密码会弹窗卡进程哦

### ISSUE THREAD

**Issue by NullYing** [evgo2017/Office2PDF#2]
测试过带密码的情况吗？带密码会弹窗卡进程哦

**Comment by evgo2017** [comment]
木有 0.0 多谢

**Comment by evgo2017** [comment]
@NullYing 最近更新了 GUI，也再试了下，会弹出，输入密码就好了，这个也该弹出来。此外 PPT 没有密码也会时常显示弹窗，不过速度比较快一闪而过。多谢。
