### ISSUE TITLE
报错：找不到元素

### ISSUE THREAD

**Issue by zibuyan** [evgo2017/Office2PDF#4]
打开 Word 进程中...
(-2147023728, '找不到元素。', None, None)
![QQ截图20201113010256](https://user-images.githubusercontent.com/65922065/98971355-01085e80-254c-11eb-9b32-be22e67f7e7c.png)

**Comment by evgo2017** [comment]
应该是因为这个 Word 文件有误，你可以用测试文件夹下的文件试试

**Comment by evgo2017** [comment]
@zibuyan 已修复，你更新下最新的代码。
